server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/indusmart_ai
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Debug Spring MVC mappings
logging.level.org.springframework.web=DEBUG

############################################
# JWT Configuration
############################################

jwt.secret=VGhpc0lzQVN1cGVyU2VjcmV0S2V5Rm9ySW5kdXNNYXJ0SldUQXV0aGVudGljYXRpb24xMjM0NTY3ODkwMTIzNDU2Nzg5MA==
jwt.expiration=86400000

################################################
# Cloudinary
################################################

cloudinary.cloud-name=et035kgp
cloudinary.api-key=962637583821223
cloudinary.api-secret=nWjMCXGPSstWAru-2JRGuGdOpEY


############################################
# Razorpay Configuration
############################################

razorpay.key.id=rzp_test_TDpvto9KwuLvbB
razorpay.key.secret=YplWGBJNQSI6Zh2RtqSWCTnM

############################################
# Swagger
############################################

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui


# ==========================
# Gmail Configuration
# ==========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=prajwalshet5018@gmail.com
spring.mail.password=crychppmbjcwtnii

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true